[package]
name = "assistant"
version = "0.1.0"
edition = "2024"

[dependencies]
serenity = { version = "0.11", features = ["client", "framework", "gateway", "rustls_backend", "model"] }
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
anyhow = "1.0"
log = "0.4"
env_logger = "0.9"